services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: codeigniter_mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-rootpassword}
      MYSQL_DATABASE: ${DB_DATABASE:-ecommerce_db}
      MYSQL_USER: ${DB_USERNAME:-dbuser}
      MYSQL_PASSWORD: ${DB_PASSWORD:-dbpassword}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - codeigniter_network
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: codeigniter_nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - codeigniter_network
    depends_on:
      - mysql
      - cloudflared

  # Cloudflare Tunnel
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: codeigniter_cloudflared
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token ${TUNNEL_TOKEN}
    networks:
      - codeigniter_network
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}

volumes:
  mysql_data:
    driver: local

networks:
  codeigniter_network:
    driver: bridge
    name: codeigniter_network
